### ISSUE TITLE
프로젝트 기본 환경 설정

### ISSUE THREAD

**Issue by namjunemy** [namjunemy/typescript_backend#1]
프로젝트 기본 환경 설정

**ToDo List**

- [x] LICENSE 파일 등록
- [x] CHANGELOG 파일 제작
- [x] .gitignore 파일 제작
- [x] GIT Template 파일 제작
